[package]
name = "craboptimize_wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
image = { version = "0.25.9", default-features = false, features = ["webp", "png", "jpeg"] }
ravif = "0.13.0"
wasm-bindgen = "0.2.108"
